workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      # iOS code signing настраивается через UI Codemagic
      # Перейдите в App settings > Distribution > iOS code signing
      # и выберите "Automatic" с вашим API ключом App Store Connect

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build iOS IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

